supabase_url = "https://jlvgoobmqiadyskzikiy.supabase.co"
supabase_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impsdmdvb2JtcWlhZHlza3ppa2l5Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0NjUxNjU3NSwiZXhwIjoyMDYyMDkyNTc1fQ.-cRZq-recXPGVO9tJQ6Jloy78DLEHTxaChqvHmb7y3I"
