supabase_url = "https://jlvgoobmqiadyskzikiy.supabase.co"
supabase_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impsdmdvb2JtcWlhZHlza3ppa2l5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1MTY1NzUsImV4cCI6MjA2MjA5MjU3NX0.WG1VdaWCb3tsuFqaFadll9TGpODvdTjsxsBS6RYcQQA"
